url: "https://bienvenuelisis.github.io/mundana-theme-jekyll-to-flutter-news-app/"

description: "Mundana Theme Jekyll to Flutter News App"

name: "jekyll-to-flutter-news-app"

instagram: "https://www.instagram.com/"

facebook: "https://www.facebook.com/"

twitter: "https://www.twitter.com/"

github: "https://github.com/bienvenuelisis/mundana-theme-jekyll-to-flutter-news-app"

email: "https://www.gmail.com/"

phone_number: "+1 (123) 456-7890"

featured_tag: "sticky"

posts_api: "/api"
